# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-15 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_populate_tweets_with_sentiments_retry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='sentiment',
            new_name='sentiment_id',
        ),
    ]
