# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-15 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180814_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='sentiment_id',
            new_name='sentiment',
        ),
    ]
