# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-20 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_populate_words_tweets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='tweet',
            new_name='tweets',
        ),
    ]
