# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-21 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_duplicate_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='value',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
