# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-01 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180901_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
